name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: tfkhdyt
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Jakarta
          commits_authoring: tfkhdyt, me@tfkhdyt.my.id, tfkhdyt@proton.me, tfkhdyt@pm.me, tfkhdyt@protonmail.com
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          plugin_languages_aliases: RenderScript:Rust
          plugin_languages_colors: github, Rust:orange
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, lua, limbo
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 30
          plugin_stars: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_people: yes
          plugin_people_types: followers
          plugin_people_limit: 48
          plugin_people_size: 50
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: push, issue, pr, release, comment
          plugin_traffic: yes
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
